# need sound effect imports 
# import playsound

print("Treasure Chest: Unknown Depths")
# playsound.playsound('treasure_chest.mp3')
print(input("Press Enter to continue..."))

print(input("Choose you character's name:. . . . "))
print("[1]Renz the Gremlin [2]Angelo the Torpe [3]Kenneth the Helper")
character = input ("Choose your character: ")
if character == "1" or character == "2" or character == "3":
    print(input(f"You chose {character}."))
    print(input("Loser heheheh. . . "))
else:
    print(input("Invalid choice. Please restart the game."))
    exit()

print(input("*You've stepped in the entrance of the unexplored dungeon."))
print(input("The place is from a rumor that the place hold an unclaimed treasure"))
print(input("And as a rookie adventurer you decided to explore the place."))
print(input("Lokking at the entrance it looked old. . . ."))
print(input("Rumors says tha it was a old military base that was abandoned years ago.")) 
print(input("And now it is a place for adventurers to explore just a week ago."))
print(input("And being opened in a small village that only few goes through since it opened. "))
print(input("You see this as an opportunity to gain fame and for. . . ."))
print(input("You can see a guard standing in front of the entrance."))                                     
print(input("*A guard approches you. . . ."))
print(input("*You can see from his eyes a distaste look. Looking at you."))
print(input("Guard: 'Hey you! You're an adventurer, aren't you?' "))
response = input("Yes/No: ")
if response == "Yes" or response == "yes":
    print(input("Guard: 'I can tell'. "))
    print(input("Guard: 'There's a fee here to enter the dungeon.' "))
    print(input("Guard: 'You must pay 1 silver coins to enter.' "))
    print(input("Guard: 'Do you have the coins?' "))
    coins = input("Yes/No: ")
    if coins == "Yes" or coins == "yes":
        print(input("*You hanbe the coins to the guard.*"))
        print(input("Guard: 'Good, you can enter.' "))
        print(input("Guard: 'Well you folks always want some thrills eh?, and that thrills always lead to their deaths.' "))
        print(input("Guard: 'Ahh, that is dumb. Instead, of helping their hometowns, they go on adventures.' "))
        print(input("Guard: 'Well i don't care, as long as you pay the fee.' "))
        print(input("Guard: 'Now, remember this kid.' "))
        print(input("Guard: 'This dungeon have been not fully explored for years as you can see that it just opened to public a week ago.' "))
        print(input("Guard: 'For what unknown reason this cave that is sitting here for god know what years now.' "))
        print(input("Guard: 'Adventurers that goes inside this cave.' "))
        print(input("Guard: 'Only few of them came back.' "))
        print(input("Guard: 'One time when i'm in post, fulfilling my shift this adventurer suddenly step outside the cave.' "))
        print(input("Guard: His face and body torn and wounded looking like he saw shit in that cave. '' "))
        print(input("Guard: 'And just sitting in the post silent and traumatized.' "))
        print(input("Guard: 'I asked about his maates and all he said is. . .'"))
        print(input("'They all died. . . .'"))
        print(input("*You ignored the guard's words, thinking that he's just messing with you and entered the dungeon.*"))
        print(input("*You enter the dungeon. . . ."))
        print(input("*You can see the darkness of the dungeon. . . ."))
        print(input("*Heared the sound of water dripping. . . ."))
        print(input("*Through and through the dungeon. . . ."))
        print(input("*You see how old the place being an old millitary that is abandoned for a long time . . . ."))
        print(input("*With the place being fairly lit, cause of the few tourches being put to bring shine the path not that far from the entrance.*"))
        print(input("*You've continue your exploration, deep in the cave."))
        print(input("And noticed few tourches as you go deeper. . . ."))
        print(input("And picked one of the tourches to light your way. . . ."))
        print(input("*You've stumbled upon a two way entrance in the cave."))
        print(input("The left path, you see a dark hallway with a litle light at the end."))
        print(input("And a some kind of sillouhette of some sort."))
        print(input("*While wondering you've. ."))
        print(input("*suddenly hear a noise. . ."))
        print(input("*You saw a fresh dead body, flesh being torn and a lifeless eye staring at you."))
        print(input("Blood still dripping from the body. . . ."))
        print(input("*You can see that the body is an adventurer, with his equipment still intact."))
        print(input("*So, feeling scared, you decided to push through and loot some of the body's equipment."))
        print(input("On the right path, beside the dead body you see at a distance a fairly lit place but dark as you go down. "))
        print(input("Which path do you choose? "))
        path = input("Left/Right or Go back: ")
        if path == "Left" or path == "left":
           print(input("*You chose the Left path.*"))
           print(input("*You treverse the left "))
           print(input("*As you go down you feel chills down your spine."))
           print(input("*And suddenly an arrow pierced through you skull."))
           print(input("*An adeventurer who thought you as the monster realizes his mistake and runs."))
           print(input("THE END: Miss input"))
        elif path == "Right" or path == "right":
            print(input("*You chose the Right path.*"))
            print(input("*Holding the tourch you pushed through and saw a lever just hangaing in the side of the hallway. "))
            pull = (input("Do you pull the lever? Yes/No: "))
            if pull == "Yes" or pull == "yes" :
                print(input("*A boulder appeared and crushed you alive."))
                print(input("THE END: Whomp"))
            elif pull == "No" or pull == "no":
                print(input("*You continue to go through the path."))
                print(input("*And see two tresure chest."))
                print(input("*One red chest is tells the truth while the blue chest one lies."))
                print(input("*If you pick the wrong chest the chest will kill you."))
                print(input("*You can only ask one question to one chest."))
                print(input("What will you do?"))
                color = (input("Ask the red one/Ask the blue one? Red/Blue?"))
                if color == "red" or color == "Red" :
                    print(input("*You ask the red chest if which one is the the tresure?"))
                    print(input("Red Chest : Uhhhhh, Idk."))
                    print(input("Uhhhhhh. What?"))
                    chest = (input("'Red Chest or Blue Chest'"))
                    if chest == "Red" or chest == "red" :
                        print(input("You pick the red chest and you open it slowly. "))
                        print(input("And the feel of finally attaining the rich and fame you;ve been longed for."))
                        print(input("You remember yourself as a kid feeling the warmth of the love you see and now as an adult you thinnking of attaining that again."))
                        print(input("Now as you openned the chest with a smile in your face a you see a mouth and swallow you half."))
                        print(input("THE END: Mimic"))
                        exit()
                    elif chest == "Blue" or chest == "blue" :
                        print(input("You've pickewd the blue chest."))
                        print(input("And as you opened the chest you slowly see a glowing sillohuette."))
                        print(input("And when you opened it you see.."))
                        print(input("you see. . . ."))
                        print(input("A golden retriver."))
                        print(input("It licked you and bark in a freindly manner."))
                        print(input("You picked the dog and pet it."))
                        print(input("You said 'You're my friend now'."))
                        print(input("Then accompanied the dog outside the cave."))
                        print(input("TRUE ENDING: The friends we made along the way."))
                        exit()
                    else:
                        print(input("Invalid choice. Please restart the game."))
                elif color == "blue" or color == "Blue" :
                    print(input("Uh i think that the chance of picking the right chest are 50/50 between the two chest and i think, if you think the chances and probability of think you can think that your chances are near 50%. . . . . "))
                    print(input("And by statistics and with that in mind we can determine the process of it. With this, something came up to my head thats is the Statistics and Probability that i take when i was taking classes in my early days."))
                    print(input("And was a tough one we learned the probability of things we play or happened in our lives."))
                    print(input("And some advanced things that I somewhat forgoten, maybe I didn't listen but with knowledge I see that we came sum the two choices we are given."))
                    print(input("And that is the meaning of life."))
                    chest = (input("'Red Chest or Blue Chest'"))
                    if chest == "Red" or chest == "red" :
                        print(input("You pick the red chest and you open it slowly. "))
                        print(input("And the feel of finally attaining the rich and fame you;ve been longed for."))
                        print(input("You remember yourself as a kid feeling the warmth of the love you see and now as an adult you thinnking of attaining that again."))
                        print(input("Now as you openned the chest with a smile in your face a you see a mouth and swallow you half."))
                        print(input("THE END: Mimic"))
                        exit()
                    elif chest == "Blue" or chest == "blue" :
                        print(input("You've pickewd the blue chest."))
                        print(input("And as you opened the chest you slowly see a glowing sillohuette."))
                        print(input("And when you opened it you see.."))
                        print(input("you see. . . ."))
                        print(input("A golden retriver."))
                        print(input("It licked you and bark in a freindly manner."))
                        print(input("You picked the dog and pet it."))
                        print(input("You said 'You're my friend now'."))
                        print(input("Then accompanied the dog outside the cave."))
                        print(input("TRUE ENDING: The friends we made along the way."))
                        exit()
                    else:
                        print(input("Invalid choice. Please restart the game."))

                else:
                    print(input("Invalid choice. Please restart the game."))
                    exit()   
            else:
                print(input("Invalid choice. Please restart the game."))
            exit() 
        elif path == "Go back" or path == "go back" :
            print(input("*You decided to go back and said.*"))
            print(input("Fuck this shit, I ain't going to be on some scary shit."))
            print(input("THE END: Fuck that cave."))
            exit()
        else:
            print(input("Invalid choice. Please restart the game."))
            exit()            
    elif coins == "No" or coins == "no":
        print(input("Guard: 'You don't have the coins?' "))
        print(input("Guard: 'Then you can't enter.' "))
        print(input("Guard: 'Come back when you have the coins.' "))
        # playsound.playsound('game_over.mp3') 
        print(input("GAME OVER: Broke"))
        exit()
    else:
        print(input("Guard: 'Invalid response. Please restart the game.' "))
        exit()
elif response == "No" or response == "no":
    print(input("Guard: 'Looking well equipped, are you?'"))
    print(input("Guard: 'Well, civillians aren't allowed in here.' "))
    print(input("Guard: 'Piss off.'")) 
    # playsound.playsound('game_over.mp3') 
    print(input("GAME OVER: Civillian."))
    exit()
else:
    print(input("Guard: 'Invalid response. Please restart the game.' "))
    exit()